### ISSUE TITLE
Implement a search function to search through the terminal

### ISSUE THREAD

**Issue by lanoxx** [lanoxx/tilda#159]
gnome-panel has this, we should have it too.

**Comment by lanoxx** [comment]
Should be activated with CTRL+SHIFT+F by default and keyboard shortcut should be configurable.

**Comment by lanoxx** [comment]
This is just an quick and dirty implementation to see whats necessary to get things working. I imagine the search bar should be hidden by default and be shown on CTRL+SHIFT+F. There should be the commonly used options to configure search:

 * Case Insensitive Search
 * Regex search (default to non regex)
 * We need automatic wrap around (and show a label when we wrap around?)
 * Maybe an option to search in all tabs?

Todos: 
 * Add a close button to hide the search bar
 * Add configurable short cut to show the search bar
 * Hide search bar by default
 * Implement the options mentioned above

@pik Would you be interested to help me with this?

**Comment by pik** [comment]
I'd like to help but I don't think I will have time to look at it until this weekend.

**Comment by lanoxx** [comment]
No problem, I will probably not look at it before either. The patch from yesterday was just a quick hack to see how much work it would really be. If you do work on this just drop a message here, so we don't do something redundantly.

**Comment by pik** [comment]
Will do, btw how do you feel about the dialog-style search box vs. the docked-style search-box? I personally feel the docked style is much nicer in a text-editor, but I haven't tried either one much in a terminal.

**Comment by lanoxx** [comment]
I would prefer the docked style - if it works well. There are some issues that  I can think of:

 * Changing he height of the terminal (when the search bar becomes visible) could affect the shell in some way, but I am not sure if thats really an issue. 
 * The searchbar should look nice if the terminals width is for some reason very small. Maybe pop it out in a dialog in that case?
 * I think we have some animation code that scales down the terminal to a very small size when its pulled up/down, we will have to see how that affects the searchbar when tilda is pulled while the bar is visible.

If these turn out to be no problem, then lets go with the docked style, otherwise we create a dialog. The problems I have with a dialog it that one always needs to ALT+TAB between the window and the dialog while searching. With the docked style we could just listen to `ESC` and then focus the terminal again and/or close the searchbar.

**Comment by pik** [comment]
Yeah Docked style sounds better - the minus is that it's hard to fit whole word check-boxes into a dock e.g. `Wrap Around`, `Match CaseOnly` etc. so probably we should use small-icons with tooltips (Sublime does this). 
I'm going to try and get various search-options to work today as well as a hot-key to show/hide the search-bar.

**Comment by lanoxx** [comment]
I added another commit to focus the search entry when the search bar is toggled on: 3c6223253fe267bea3125bd9746f9176727d2d8b

**Comment by lanoxx** [comment]
The showing/hiding of the label and the wrap around flag should work now too. I am still thinking if it makes sense to change the label message depending on whether the search hit the search direction.

I think that it should be possible to search by pressing enter when the GtkEntry has focus, but so far I was not able to get that working.

**Comment by pik** [comment]
@lanoxx 
It's looking good. Changing the warning and perhaps also changing bar appearance (top/bottom of the terminal) would be good additions. Another might be to hide the warning if the search has hit bottom but entry-text has changed? 

I'll add the Enter-key.

**Comment by lanoxx** [comment]
@pik,
Good point. We might need to connect to the changed signal and reset the last search flag if the text has changed. Because we dont actually know if the new text might not give a result without wrapping around.

**Comment by pik** [comment]
oh, I was just going to suggest adding a text_entry pointer to search and to drop the warning if text_entry has changed (it's still the same search from the top, only no warning for a new entry).

**Comment by lanoxx** [comment]
I just commited one patch to hide the label when the text changed. I used the `GtkEditable::changed` signal instead of `key-press`, as that also catches copy/paste changes.

**Comment by lanoxx** [comment]
See: c7c6b288739aa0814502b13d5b3427cdcc52bebd

**Comment by lanoxx** [comment]
I added commit 3fd33c3ca77096cffe5a58762b4c39a6fde83d47 to keep the tw->terms structure synchronized with the tab order. This fixes a problem that prevented the Terminal to gain focus after the search bar was hidden. I used your solution to lookup the VteTerminal pointer relative from the tab child, but that might break if the UI is changed. However I could not find a way to get the old position of the tab in the callback. Another solution might be to track the number of the currently active tab in the tw structure, since only active tabs can be dragged.

**Comment by lanoxx** [comment]
I actually found a better solution: efebf416244e97cf603dce5dd42614b16099cfdc

**Comment by lanoxx** [comment]
@pik I just cleanup the commits and rebased everything on master. I think this can be merged into master now. Do you have any final comments?

**Comment by pik** [comment]
@lanoxx 
So one minor comment is I think I was wrong about preferring the enums over booleans e.g. https://github.com/pik/tilda/commit/f10055487188c9d22116e11bc3a9103e948187e2 is definitely more terse. 

Either way it looks good to me.

**Comment by lanoxx** [comment]
Ok, it took some time to rebase it, but I wanted to eliminate the enums from all commits, so this is really a clean series of commits.

I also added one more small feature, the search bar can now be hidden by using the escape key when the search entry has focus, that makes it easier to hide the search bar

Thanks a lot for helping with this feature. :+1:
